# Generated by Django 3.0.2 on 2020-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
